name=Potentiometer
version=1.0.0
author=Arthur Assis, Ícaro Gomes
maintainer=Arthur Assis <axassis11@gmail.com>
sentence=Uma biblioteca simples para leitura e mapeamento de potenciômetros.
paragraph=Esta biblioteca facilita o uso de potenciômetros no Arduino, permitindo a leitura de valores brutos, conversão automática para tensão (0V-5V) e mapeamento para intervalos personalizados, exibindo os valores no monitor serial.
category=Sensors
url=https://github.com/Arthur-PX-Assis/PotentiometerBib
architectures=*
includes=Potentiometer.h